### ISSUE TITLE
List index is out of range?

### ISSUE THREAD

**Issue by yonzk** [torrinworx/Blend_My_NFTs#100]
Python: Traceback (most recent call last):
  File "/Users/e/Library/Application Support/Blender/3.0/scripts/addons/Blend_My_NFTs-main/__init__.py", line 352, in execute
    DNA_Generator.send_To_Record_JSON(collectionSize, nftsPerBatch, save_path, enableRarity, enableLogic, logicFile, Blend_My_NFTs_Output)
  File "/Users/e/Library/Application Support/Blender/3.0/scripts/addons/Blend_My_NFTs-main/main/DNA_Generator.py", line 278, in send_To_Record_JSON
    create_nft_data()
  File "/Users/e/Library/Application Support/Blender/3.0/scripts/addons/Blend_My_NFTs-main/main/DNA_Generator.py", line 235, in create_nft_data
    DataDictionary = generateNFT_DNA(collectionSize, logicFile, enableRarity, enableLogic)
  File "/Users/e/Library/Application Support/Blender/3.0/scripts/addons/Blend_My_NFTs-main/main/DNA_Generator.py", line 192, in generateNFT_DNA
    DNAList = create_DNAList()
  File "/Users/e/Library/Application Support/Blender/3.0/scripts/addons/Blend_My_NFTs-main/main/DNA_Generator.py", line 186, in create_DNAList
    DNASetReturn |= {''.join([dnaPushToList()]) for _ in range(collectionSize - len(DNASetReturn))}
  File "/Users/e/Library/Application Support/Blender/3.0/scripts/addons/Blend_My_NFTs-main/main/DNA_Generator.py", line 186, in <setcomp>
    DNASetReturn |= {''.join([dnaPushToList()]) for _ in range(collectionSize - len(DNASetReturn))}
  File "/Users/e/Library/Application Support/Blender/3.0/scripts/addons/Blend_My_NFTs-main/main/DNA_Generator.py", line 170, in singleCompleteDNA
    singleDNA = Rarity.createDNArarity(hierarchy)
  File "/Users/e/Library/Application Support/Blender/3.0/scripts/addons/Blend_My_NFTs-main/main/Rarity.py", line 38, in createDNArarity
    variantByNum = random.choices(number_List_Of_i, weights=rarity_List_Of_i, k=1)
  File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/random.py", line 500, in choices
    total = cum_weights[-1] + 0.0   # convert to float

IndexError: list index out of range

location: <unknown location>:-1

<img width="230" alt="Screen Shot 2022-05-07 at 5 08 44 PM" src="https://user-images.githubusercontent.com/95213271/167276197-60e33c3d-aade-4e02-ad92-a12a3a3dd8e4.png">

<img width="231" alt="Screen Shot 2022-05-07 at 5 09 08 PM" src="https://user-images.githubusercontent.com/95213271/167276199-145a56d8-076a-4664-b666-d407eeee6363.png">

Im pretty new to this. I must've set something up incorrectly..

**Comment by torrinworx** [comment]
Looks like it's an issue with the `Mat` collection. Make sure all Variants are represented by collections, not objects. Hope this helps!

**Comment by yonzk** [comment]
Lets say I would like to have different positions and extra lights when a user mints a more rare Sheetcombo
