### ISSUE TITLE
error when create data

### ISSUE THREAD

**Issue by sandhunter66** [torrinworx/Blend_My_NFTs#99]
hi.. thank you for the addon.. but im facing a problem when trying to create data and generate nft.. This is the problem

Error: Python: Traceback (most recent call last):
  File "C:\Users\RYZEN 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Blend_My_NFTs-main\__init__.py", line 352, in execute
    DNA_Generator.send_To_Record_JSON(collectionSize, nftsPerBatch, save_path, enableRarity, enableLogic, logicFile, Blend_My_NFTs_Output)
  File "C:\Users\RYZEN 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Blend_My_NFTs-main\main\DNA_Generator.py", line 278, in send_To_Record_JSON
    create_nft_data()
  File "C:\Users\RYZEN 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Blend_My_NFTs-main\main\DNA_Generator.py", line 235, in create_nft_data
    DataDictionary = generateNFT_DNA(collectionSize, logicFile, enableRarity, enableLogic)
  File "C:\Users\RYZEN 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Blend_My_NFTs-main\main\DNA_Generator.py", line 192, in generateNFT_DNA
    DNAList = create_DNAList()
  File "C:\Users\RYZEN 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Blend_My_NFTs-main\main\DNA_Generator.py", line 186, in create_DNAList
    DNASetReturn |= {''.join([dnaPushToList()]) for _ in range(collectionSize - len(DNASetReturn))}
  File "C:\Users\RYZEN 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Blend_My_NFTs-main\main\DNA_Generator.py", line 186, in <setcomp>
    DNASetReturn |= {''.join([dnaPushToList()]) for _ in range(collectionSize - len(DNASetReturn))}
  File "C:\Users\RYZEN 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Blend_My_NFTs-main\main\DNA_Generator.py", line 167, in singleCompleteDNA
    singleDNA = createDNArandom()
  File "C:\Users\RYZEN 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Blend_My_NFTs-main\main\DNA_Generator.py", line 151, in createDNArandom
    randomVariantNum = random.choices(i, k=1)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\random.py", line 486, in choices
    return [population[floor(random() * n)] for i in _repeat(None, k)]
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\random.py", line 486, in <listcomp>
    return [population[floor(random() * n)] for i in _repeat(None, k)]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by xReapex** [comment]
Same problem here

**Comment by sandhunter66** [comment]
any workaround?

**Comment by torrinworx** [comment]
@mirkhayot1998, @xReapex @sandhunter66 can you provide anymore information about your setup? What version of BMNFTs are you using? Have you uninstalled all previous versions and tried a fresh download? What is the recommended limit for your collection? 

Is this the first time you've seen this error?

**Comment by sandhunter66** [comment]
im using blender 3.0 using fresh installation.

**Comment by sandhunter66** [comment]
recommended limit of my collection is 46000

**Comment by sandhunter66** [comment]
yes it is the first time i see this error.. i really hope this plugin works because i can see it is very useful for many people

**Comment by yonzk** [comment]
I'm getting the same problem trying now.. I opened my own issues comment prior to seeing this sorry. I have screen shots I feel like I've still done something wrong...

**Comment by torrinworx** [comment]
It looks like this might be an issue with the naming of an Attribute or Variant collection. I would recommend reading https://github.com/torrinworx/Blend_My_NFTs#blender-file-organization-and-structure and check over your scene one more time.
